services:
  verhulst:
    build: .
    container_name: verhulst_model
    ports:
      - "8000:8000"
    volumes:
      - ./data/simulations:/app/simulations_results
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 4G
        reservations:
          memory: 600M
    environment:
      - MAX_WORKERS=2