services:
  verhulst:
    build: .
    container_name: verhulst_model
    ports:
      - "8000:8000"
    volumes:
      - ./data/simulations:/app/simulations_results
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 1G
        reservations:
          memory: 400M
    environment:
      - PYTHONUNBUFFERED=1 # Pendiente setear la variable de entorno en Dockerfile